### ISSUE TITLE
Missing `TrepanDatasetType` package

### ISSUE THREAD

**Issue by MajlindaLlugiqi** [rconfalonieri/trepan_reloaded#1]
Hello everyone,

First of all, thank you for making your paper's implementation open source. I have managed to run your examples you have provided and ran everything smoothly. 

However, having installed the Python requirements and after trying to run your code on my own dataset I am encountering an error `No module named TrepanDatasetType` from here https://github.com/rconfalonieri/trepan_reloaded/blob/main/utils/pytorchmodels/threshold-xor.py#L8

Is there a way to get access to this package? I could not find anything about it online.

Thank you in advance.

Best regards,
Majlinda Llugiqi

**Comment by MajlindaLlugiqi** [comment]
It seems that it was imported incorrectly:
I tried `from FeedForwardNetwork import TrepadDatasetType as TDT` instead of `import TrepadDatasetType as TDT` and it worked

**Comment by rconfalonieri** [comment]
You were quicker than me in replying. You do not have to use this part of the code though.
