### ISSUE TITLE
Where does the IG change take place? (IG'=IG*IC)

### ISSUE THREAD

**Issue by MajlindaLlugiqi** [rconfalonieri/trepan_reloaded#4]
Hello,

I was wondering if the IG'=IG*IC is done in tree.c file. I saw that there is the line of code `split->gain = inf_content*split->gain;` that does this, but when I change it, the output is the same. Even if I change  `printf("\nevaluate splits: inf_content %f",split->frequency);` to `'printf("\nevaluateeeee splits: inf_content %f",split->frequency);'` it still prints: evaluate splits: ... that indicates the printing isn't from here, and I couldn't find it, so I was wondering where you're updating the IG?

Best,
Majlinda

**Comment by rconfalonieri** [comment]
Hi there.
 
Yes, IG'=IG*IC is done in the tree.c file, in the place where you pointed out.
You will see any changes in the output only after you will have recompiled the code.
This can be done by running:

sh trepan-compile.sh
To see any change to the code like the one you are trying to do, you will have to compile it first.

Best regards,
Roberto.

**Comment by MajlindaLlugiqi** [comment]
Thank you!
